#!/usr/bin/env python
# Generate a compiled-in C++ pool table from the editable memory-map YAML, so the PC build can stand up
# the real Burnout pool set (GameDataModule::CreatePools) without a runtime YAML parser.
#
# Pipeline: tools/assets/memory_map/export_yaml.py (XEX -> progress/memory_map_artist.yaml, editable) ->
#           tools/assets/memory_map/generate_header.py (YAML -> BrnMemoryMapData.h, build input).
#
# Usage: py tools/assets/memory_map/generate_header.py
import os, re

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
YAML = os.path.join(ROOT, 'progress', 'memory_map_artist.yaml')
OUT  = os.path.join(ROOT, 'b5-decomp', 'src', 'GameSource', 'Resource', 'BrnMemoryMapData.h')

def parse_pools(text):
    pools = []
    cur = None
    in_pools = False
    in_heaps = False
    for raw in text.splitlines():
        line = raw.rstrip()
        if line.startswith('pools:'):
            in_pools = True; continue
        if not in_pools:
            continue
        m = re.match(r'  - id:\s*(-?\d+)', line)
        if m:
            if cur: pools.append(cur)
            cur = dict(id=int(m.group(1)), name='', nodes=0, maxres=0, maximp=0,
                       defrag=False, deps=[], heaps=[])
            in_heaps = False
            continue
        if cur is None:
            continue
        m = re.match(r'    name:\s*(.+)', line)
        if m:
            n = m.group(1).strip()
            if n.startswith("'") and n.endswith("'"): n = n[1:-1].replace("''", "'")
            cur['name'] = n; continue
        m = re.match(r'    max_heap_nodes:\s*(\d+)', line)
        if m: cur['nodes'] = int(m.group(1)); continue
        m = re.match(r'    max_resources:\s*(\d+)', line)
        if m: cur['maxres'] = int(m.group(1)); continue
        m = re.match(r'    max_imports:\s*(\d+)', line)
        if m: cur['maximp'] = int(m.group(1)); continue
        m = re.match(r'    allow_defragmentation:\s*(\w+)', line)
        if m: cur['defrag'] = (m.group(1) == 'true'); continue
        m = re.match(r'    dependencies:\s*\[([^\]]*)\]', line)
        if m:
            cur['deps'] = [int(x) for x in m.group(1).split(',') if x.strip()]; continue
        if line.startswith('    heaps:'):
            in_heaps = True; continue
        if in_heaps:
            m = re.match(r'\s*-\s*\{\s*type:\s*(\d+),\s*size:\s*(0x[0-9A-Fa-f]+),\s*align:\s*(\d+)\s*\}', line)
            if m:
                cur['heaps'].append((int(m.group(1)), int(m.group(2), 16), int(m.group(3))))
    if cur: pools.append(cur)
    return pools

def parse_allocators(text):
    """Parse the five `allocators:` record tables (single-line mappings)."""
    tables = {'raw_resources': [], 'linear': [], 'heap': [], 'rw_linear': [], 'rw_general': []}
    cur = None
    in_alloc = False
    for raw in text.splitlines():
        line = raw.rstrip()
        if line.startswith('allocators:'):
            in_alloc = True; continue
        if not in_alloc:
            continue
        m = re.match(r'  (\w+):\s*$', line)
        if m:
            cur = m.group(1)
            continue
        if cur is None or cur not in tables:
            continue
        m = re.match(r'    - \{ bank:\s*(\d+),\s*name:\s*([^,]+),\s*parent:\s*(\d+),\s*'
                     r'(?:size:\s*(0x[0-9A-Fa-f]+)|desc:\s*\[(.*)\])\s*\}\s*$', line)
        if not m:
            continue
        entry = dict(bank=int(m.group(1)), name=m.group(2).strip().strip("'"),
                     parent=int(m.group(3)), size=[0]*5, align=[1]*5)
        if m.group(4):
            entry['size'][0] = int(m.group(4), 16)
            entry['align'][0] = 16
        else:
            for dm in re.finditer(r'\{\s*type:\s*(\d+),\s*size:\s*(0x[0-9A-Fa-f]+),\s*align:\s*(\d+)\s*\}', m.group(5)):
                t = int(dm.group(1))
                entry['size'][t] = int(dm.group(2), 16)
                entry['align'][t] = int(dm.group(3))
        tables[cur].append(entry)
    return tables

def main():
    text = open(YAML, encoding='latin1').read()
    pools = parse_pools(text)
    allocators = parse_allocators(text)
    L = []
    L.append('// GENERATED by tools/assets/memory_map/generate_header.py from progress/memory_map_artist.yaml -- do not edit by hand.')
    L.append('// The real Burnout X360 (ARTIST) resource-pool definition table (from the binary memory map')
    L.append('// unk_82F2A788). GameDataModule::CreatePools stands these up via PoolModule::CreatePool. Per-type')
    L.append('// muHeapSize is the pool\'s heap budget for memory type t (0 = type unused); the pool\'s total')
    L.append('// per-type region (descriptor) is heapSize + the pool overhead (entry arrays / hash / heap nodes),')
    L.append('// computed at create time via Pool::GetOverheadMemoryRequired.')
    L.append('#pragma once')
    L.append('')
    L.append('#include "types.hpp"')
    L.append('')
    L.append('namespace BrnResource')
    L.append('{')
    L.append('    struct MemoryMapPoolDef')
    L.append('    {')
    L.append('        s32         miId;')
    L.append('        const char* mpcName;')
    L.append('        s32         miMaxHeapNodes;')
    L.append('        s32         miMaxResources;')
    L.append('        s32         miMaxImports;')
    L.append('        bool        mbAllowDefrag;')
    L.append('        u32         mauHeapSize[3];   // per memory type (0 = unused)')
    L.append('        u32         mauHeapAlign[3];')
    L.append('        s32         miNumDeps;')
    L.append('        s32         maiDeps[8];        // dependent pool ids (import sources)')
    L.append('    };')
    L.append('')
    L.append('    static const MemoryMapPoolDef KAC_MEMORY_MAP_POOLS[] =')
    L.append('    {')
    for p in pools:
        sz = [0, 0, 0]; al = [0, 0, 0]
        for (t, s, a) in p['heaps']:
            if 0 <= t < 3: sz[t] = s; al[t] = a
        deps = p['deps'][:8]
        depstr = ', '.join('%d' % d for d in deps) if deps else '0'
        cname = p['name'].replace('"', '\\"')
        L.append('        { %d, "%s", %d, %d, %d, %s, {0x%X,0x%X,0x%X}, {%d,%d,%d}, %d, {%s} },'
                 % (p['id'], cname, p['nodes'], p['maxres'], p['maximp'],
                    'true' if p['defrag'] else 'false',
                    sz[0], sz[1], sz[2], al[0], al[1], al[2], len(deps), depstr))
    L.append('    };')
    L.append('')
    L.append('    static const s32 KI_NUM_MEMORY_MAP_POOLS = %d;' % len(pools))
    L.append('')
    L.append('    // The memory map\'s five allocator record tables (unk_82F2A788 header counts @+16..+32,')
    L.append('    // table offsets @+44..+60): the definitions GameDataModule::CreateAllocators (0x8266DD00)')
    L.append('    // publishes as type-10 (raw resource) / 14 (linear + heap) / 11 (rw linear) / 12 (rw')
    L.append('    // general) create requests. miBankId keys the AllocatorList registry; miParentBankId is')
    L.append('    // the X360 CreateBanks-tree parent the leaf bank is carved from. Descriptor lanes are the')
    L.append('    // rw 5-entry {size, align} set (only lanes 0/2 are populated by the map).')
    L.append('    struct MemoryMapAllocatorDef')
    L.append('    {')
    L.append('        s32         miBankId;')
    L.append('        const char* mpcName;')
    L.append('        s32         miParentBankId;')
    L.append('        u32         mauSize[5];    // per rw memory-type lane (0 = unused)')
    L.append('        u32         mauAlign[5];')
    L.append('    };')
    L.append('')
    tbl_names = [('raw_resources', 'KAC_MEMORY_MAP_RAW_ALLOCATORS',       'KI_NUM_MEMORY_MAP_RAW_ALLOCATORS'),
                 ('linear',        'KAC_MEMORY_MAP_LINEAR_ALLOCATORS',    'KI_NUM_MEMORY_MAP_LINEAR_ALLOCATORS'),
                 ('heap',          'KAC_MEMORY_MAP_HEAP_ALLOCATORS',      'KI_NUM_MEMORY_MAP_HEAP_ALLOCATORS'),
                 ('rw_linear',     'KAC_MEMORY_MAP_RWLINEAR_ALLOCATORS',  'KI_NUM_MEMORY_MAP_RWLINEAR_ALLOCATORS'),
                 ('rw_general',    'KAC_MEMORY_MAP_RWGENERAL_ALLOCATORS', 'KI_NUM_MEMORY_MAP_RWGENERAL_ALLOCATORS')]
    for key, arr, cnt in tbl_names:
        rows = allocators.get(key, [])
        L.append('    static const MemoryMapAllocatorDef %s[] =' % arr)
        L.append('    {')
        for e in rows:
            L.append('        { %d, "%s", %d, {0x%X,0x%X,0x%X,0x%X,0x%X}, {%d,%d,%d,%d,%d} },'
                     % (e['bank'], e['name'].replace('"', '\\"'), e['parent'],
                        e['size'][0], e['size'][1], e['size'][2], e['size'][3], e['size'][4],
                        e['align'][0], e['align'][1], e['align'][2], e['align'][3], e['align'][4]))
        L.append('    };')
        L.append('    static const s32 %s = %d;' % (cnt, len(rows)))
        L.append('')
    L.pop()   # trailing blank
    L.append('}')
    text = '\n'.join(L) + '\n'
    open(OUT, 'w', newline='\n').write(text)
    print('wrote %d pool defs -> %s' % (len(pools), os.path.normpath(OUT)))

if __name__ == '__main__':
    main()
