"""Regression tests with synthetic saves (no private player save is committed)."""

from pathlib import Path
import struct
import sys
import tempfile
import unittest
import zlib

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import convert_xenia_save as c


def mc02(payload):
    head = struct.pack(">6I", 0x4D433032, len(payload) + 28, 0, len(payload), 0, c.mc02_crc(payload))
    return head + struct.pack(">I", c.mc02_crc(head)) + payload


def profile():
    image = bytearray(c.IMAGE_SIZE)
    for offset, value in ((0, 28), (c.REVENGE, 6), (c.OPTIONS, 12), (c.DLC, 6), (c.DLC_OPTIONS, 1)):
        struct.pack_into(">I", image, offset, value)
    return image


class ConverterTests(unittest.TestCase):
    def test_console_crc_known_header(self):
        # Captured MC02 header; reference CRC is from the console file, not
        # generated by the function under test. Also pins the short-input arm.
        head = bytes.fromhex("4d4330320004001c00000000000400000000000046ab5e75")
        self.assertEqual(c.mc02_crc(head), 0xE03F45E9)
        self.assertEqual(c.mc02_crc(b"abc"), 0)
        self.assertEqual(c.mc02_crc(b"\x01\x23\x45\x67"), 0x01234567)

    def test_mixed_width_fields_and_padding(self):
        image = profile()
        image[4:36] = b"Player's name, intact".ljust(32, b"\0")
        struct.pack_into(">4f", image, 48, 3100.25, -2.5, -1937.125, 1.0)
        struct.pack_into(">Q", image, 80, 0xA7E5D580DF6B8000)
        struct.pack_into(">I", image, 604, 1)
        struct.pack_into(">Q", image, 624, 0x0123456789ABCDEF)
        image[632:636] = bytes([3, 7, 1, 0xCD])
        struct.pack_into(">fI", image, 636, 0.85, 2)
        struct.pack_into(">IH", image, 28784, 1234, 0x1234)
        image[28790:28792] = b"\xCD\xEF"
        struct.pack_into(">Q", image, 58920, (1 << 0) | (1 << 63))
        struct.pack_into(">h", image, 96424, 123)
        struct.pack_into(">I", image, c.DLC + 1968, 1)
        image[c.DLC+8:c.DLC+24] = b"Rival".ljust(16, b"\0")
        struct.pack_into(">QQI", image, c.DLC+24, 0x1020304050607080, 0xAABBCCDDEEFF1234, 123456)
        image[-100:] = bytes(range(100))
        out = c.swap_profile_fields(bytes(image))
        self.assertEqual(struct.unpack_from("<4f", out, 48), (3100.25, -2.5, -1937.125, 1.0))
        self.assertEqual(struct.unpack_from("<Q", out, 80)[0], 0xA7E5D580DF6B8000)
        self.assertEqual(struct.unpack_from("<Q", out, 624)[0], 0x0123456789ABCDEF)
        self.assertEqual(out[632:636], image[632:636])
        self.assertAlmostEqual(struct.unpack_from("<f", out, 636)[0], 0.85, places=6)
        self.assertEqual(struct.unpack_from("<H", out, 28788)[0], 0x1234)
        self.assertEqual(out[28790:28792], b"\xCD\xEF")
        self.assertEqual(struct.unpack_from("<Q", out, 58920)[0], (1 << 0) | (1 << 63))
        self.assertEqual(struct.unpack_from("<h", out, 96424)[0], 123)
        self.assertEqual(out[c.DLC+8:c.DLC+24], image[c.DLC+8:c.DLC+24])
        self.assertEqual(struct.unpack_from("<QQI", out, c.DLC+24), (0x1020304050607080, 0xAABBCCDDEEFF1234, 123456))
        self.assertEqual(out[4:36], image[4:36])
        self.assertEqual(out[-100:], image[-100:])
        self.assertEqual(c.swap_profile_fields(out), image)

    def test_dates_are_u64_not_two_independent_u32(self):
        image = profile()
        ticks = 0x01DB1434BB3F3BE0
        # Licence issue date, a mugshot capture date and a revenge date.
        for offset in (117980, 112240 + 24, c.REVENGE + 8 + 72):
            image[offset:offset+4] = b"\x01\xCD\xCD\xCD"
            struct.pack_into(">Q", image, offset + 4, ticks)
        out = c.swap_profile_fields(image)
        for offset in (117980, 112240 + 24, c.REVENGE + 8 + 72):
            self.assertEqual(out[offset:offset+4], b"\x01\xCD\xCD\xCD")
            self.assertEqual(struct.unpack_from("<II", out, offset+4), (0xBB3F3BE0, 0x01DB1434))

    def test_options_preserve_bools_and_swap_ids(self):
        image = profile()
        route = c.OPTIONS + 8
        struct.pack_into(">Q", image, route, 0x0102030405060708)
        struct.pack_into(">III", image, route+128, 42, 1, 5)
        image[route+1468:route+1472] = b"\x01\x00\x01\xCD"
        struct.pack_into(">II", image, c.OPTIONS+0x735C, 5, 10)
        image[c.OPTIONS+0x7368:c.OPTIONS+0x7370] = bytes(range(8))
        out = c.swap_profile_fields(image)
        self.assertEqual(struct.unpack_from("<Q", out, route)[0], 0x0102030405060708)
        self.assertEqual(struct.unpack_from("<III", out, route+128), (42, 1, 5))
        self.assertEqual(out[route+1468:route+1472], b"\x01\x00\x01\xCD")
        self.assertEqual(struct.unpack_from("<II", out, c.OPTIONS+0x735C), (5, 10))
        self.assertEqual(out[c.OPTIONS+0x7368:c.OPTIONS+0x7370], bytes(range(8)))

    def test_mc02_damage_and_wrong_size_rejected(self):
        good = mc02(bytes(profile()))
        for offset in (8, 25, 1000):
            bad = bytearray(good)
            bad[offset] ^= 1
            with self.assertRaises(c.SaveError):
                c.read_mc02(bytes(bad), c.IMAGE_SIZE, "Profile")
        for bad in (good[:-1], good+b"\0", b"CON " + good[4:]):
            with self.assertRaises(c.SaveError):
                c.read_mc02(bad, c.IMAGE_SIZE, "Profile")

    def test_versions_counts_and_overflow_rejected(self):
        for offset, value in ((0, 27), (c.OPTIONS, 99), (604, 513), (616, 176),
                              (c.REVENGE+30008, 250), (c.DLC+2784, 33), (58912, 0xFFFFFFFF)):
            image = profile()
            struct.pack_into(">I", image, offset, value)
            with self.subTest(offset=offset), self.assertRaises(c.SaveError):
                c.validate_profile(image)
        image = profile()
        struct.pack_into(">I", image, 604, 512)
        struct.pack_into(">I", image, c.DLC+2776, 1)
        with self.assertRaises(c.SaveError):
            c.validate_profile(image)

    def test_photo_bytes_and_hash_and_invalid_placeholder(self):
        # Red/green BC1 endpoints and distinct index bytes, in Xenos 8IN16.
        pc_block = bytes.fromhex("00f8e00712345678")
        console_pixels = bytes.fromhex("f80007e034127856") * 1200
        blob = bytearray(c.MUGSHOT_SIZE * c.MUGSHOT_COUNT)
        struct.pack_into(">II", blob, 0, c.MUGSHOT_MAGIC, zlib.crc32(console_pixels)^0xFFFFFFFF)
        blob[8:c.MUGSHOT_SIZE] = console_pixels
        # A pre-existing unreadable blank photo stays unreadable.
        struct.pack_into(">II", blob, c.MUGSHOT_SIZE, c.MUGSHOT_MAGIC, 0)
        out, invalid = c.convert_mugshots(bytes(blob))
        self.assertEqual(out[8:16], pc_block)
        self.assertEqual(struct.unpack_from("<II", out), (c.MUGSHOT_MAGIC, zlib.crc32(pc_block*1200)^0xFFFFFFFF))
        self.assertEqual(invalid, [1])
        self.assertEqual(struct.unpack_from("<II", out, c.MUGSHOT_SIZE), (c.MUGSHOT_MAGIC, 0))
        self.assertEqual(out[c.MUGSHOT_SIZE+8:2*c.MUGSHOT_SIZE], bytes(9600))

    def test_b5sv_checksum_size_and_magic(self):
        image = c.swap_profile_fields(profile())
        data = c.make_container(image, b"")
        self.assertEqual(data[:4], b"VS5B")  # integer magic, stored LITTLE endian
        self.assertEqual(len(data), 312 + c.IMAGE_SIZE)
        self.assertEqual(c.read_container(data), (image, b""))
        bad = bytearray(data)
        bad[-1] ^= 1
        for invalid in (bytes(bad), data[:-1], data+b"extra"):
            with self.assertRaises(c.SaveError):
                c.read_container(invalid)

    def test_source_selection_and_exclusive_output(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            save = root / "content" / c.TITLE_ID / "00000001" / "Profile"
            save.mkdir(parents=True)
            src = save / "Profile"
            original = mc02(bytes(profile()))
            src.write_bytes(original)
            # Decoy must never be chosen.
            decoy = save.with_name("Profile_unlocked")
            decoy.mkdir()
            (decoy / "Profile").write_bytes(b"bad")
            output = root / "converted" / "Profile.sav"
            self.assertEqual(c.resolve_source(root), src.resolve())
            c.convert(root)  # check-only
            self.assertFalse(output.exists())
            report = c.convert(root, output)
            self.assertEqual(report["output_size"], 312+c.IMAGE_SIZE)
            for target in (src, output):
                with self.assertRaises(c.SaveError):
                    c.convert(root, target)
            self.assertEqual(src.read_bytes(), original)
            c.read_container(output.read_bytes())

    def test_missing_gallery_file_rejected_without_output(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            image = profile()
            struct.pack_into(">I", image, 112240+1120, 1)
            (root / "Profile").write_bytes(mc02(image))
            output = root / "result.sav"
            with self.assertRaisesRegex(c.SaveError, "Mugshots file is missing"):
                c.convert(root, output)
            self.assertFalse(output.exists())


if __name__ == "__main__":
    unittest.main()
