#!/usr/bin/env python
# Export the X360 ARTIST binary memory map (unk_82F2A788) to a human-readable / editable YAML.
#
# The memory map is the data table BrnResource::GameDataModule::CreatePools (0x8266DB88) iterates to
# create the game's 16 memory banks + 27 resource pools. This tool reads it straight from the decrypted
# XEX and emits a YAML spec (banks + pools with their decoded fields), so the pool set can be reviewed/
# edited and later loaded by the PC build (instead of carrying the raw big-endian blob).
#
# Usage: py tools/export_memory_map_yaml.py [out.yaml]
#   default out = progress/memory_map_artist.yaml
#
# FIELD MAP (172-byte MemoryMapPool, RE'd empirically from the blob + the X360 CreatePools/Pool::InitPool
# reads; the 172B record has NO standalone header/DWARF -- see the gamedatamodule-scoping memory). Fields
# at +0/+4 are the request header the X360 overwrites (mpUser/eventId) and are not pool data; the pool's
# own id/type is at +8. Names are inline char[32]. Some fields (ref-count threshold, dependency stride) are
# best-effort and flagged; sizes/aligns/counts/ids/deps are confident.
import struct, os, sys

XEX     = os.path.join(os.path.dirname(__file__), '..', 'IDA Files', 'BURNOUT_X360_ARTIST_Decrypted_Uncompressed.xex')
MAP_VA  = 0x82F2A788
NUM_MEM_TYPES = 3

def load_blob():
    data = open(XEX, 'rb').read()
    pe = 0x3000
    assert data[pe:pe+2] == b'MZ'
    e_lfanew = struct.unpack_from('<I', data, pe+0x3C)[0]
    peoff = pe + e_lfanew
    assert data[peoff:peoff+4] == b'PE\x00\x00'
    imgbase = struct.unpack_from('<I', data, peoff+24+28)[0]
    return data, pe + (MAP_VA - imgbase)

def main():
    out = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(__file__), '..', 'progress', 'memory_map_artist.yaml')
    data, base = load_blob()
    def u32(off):  return struct.unpack_from('>I', data, base+off)[0]
    def s32(off):  return struct.unpack_from('>i', data, base+off)[0]
    def u8(off):   return data[base+off]
    def name(off, span=32):
        raw = data[base+off:base+off+span]
        z = raw.find(b'\x00')
        return raw[:z if z >= 0 else span].decode('latin1')

    ver, plat, nBanks, nPools = u32(0), u32(4), u32(8), u32(12)
    pBanks, pPools = u32(36), u32(40)
    BANK_SZ = (pPools - pBanks) // nBanks
    POOL_SZ = (u32(44) - pPools) // nPools   # pRaw - pPools

    L = []
    L.append('# Burnout Paradise X360 (ARTIST) memory map -- banks + resource pools.')
    L.append('# Generated by tools/export_memory_map_yaml.py from unk_82F2A788 in the decrypted XEX.')
    L.append('# Sizes are bytes (hex). Pool id == the resource memory-type id. Edit + load via the PC build.')
    L.append('version: %d' % ver)
    L.append('platform: %d' % plat)
    L.append('')
    L.append('banks:')
    for i in range(nBanks):
        L.append('  - index: %d' % i)
        L.append('    name: %s' % yamlstr(name(pBanks + BANK_SZ*i)))
    L.append('')
    L.append('pools:')
    for i in range(nPools):
        p = pPools + POOL_SZ*i
        pid      = s32(p+8)
        pname    = name(p+12)
        nTypes   = u32(p+44)
        maxNodes = u32(p+48)
        maxRes   = u32(p+80)
        maxImp   = u32(p+84)
        refThr   = u32(p+88)
        nDeps    = u32(p+92)
        allocA   = u32(p+160)
        allocB   = u32(p+164)
        allowDfg = bool(u8(p+171))
        deps     = [u32(p+96 + 4*d) for d in range(min(nDeps, 16))]
        L.append('  - id: %d' % pid)
        L.append('    name: %s' % yamlstr(pname))
        L.append('    num_mem_types: %d' % nTypes)
        L.append('    max_heap_nodes: %d' % maxNodes)
        L.append('    max_resources: %d' % maxRes)
        L.append('    max_imports: %d' % maxImp)
        if refThr:   L.append('    ref_count_threshold: %d   # [best-effort]' % refThr)
        L.append('    allow_defragmentation: %s' % ('true' if allowDfg else 'false'))
        L.append('    allocator_indices: [%d, %d]   # [linear?, heap?] -- into the map allocator arrays' % (allocA, allocB))
        if deps:
            L.append('    dependencies: [%s]   # pool ids this pool imports from' % ', '.join(str(d) for d in deps))
        # per-memory-type {size, align} (the X360 sizes the pool's heap per type from these)
        L.append('    heaps:')
        any_heap = False
        for t in range(NUM_MEM_TYPES):
            sz = u32(p + 56 + 8*t)
            al = u32(p + 60 + 8*t)
            if sz == 0:
                continue
            any_heap = True
            L.append('      - { type: %d, size: 0x%08X, align: %d }' % (t, sz, al))
        if not any_heap:
            L[-1] = '    heaps: []'

    text = '\n'.join(L) + '\n'
    os.makedirs(os.path.dirname(out), exist_ok=True)
    open(out, 'w', newline='\n').write(text)
    print('wrote %d banks + %d pools -> %s' % (nBanks, nPools, os.path.normpath(out)))

def yamlstr(s):
    # quote if it contains anything that needs it
    if s == '' or any(c in s for c in ':#') or s != s.strip():
        return "'%s'" % s.replace("'", "''")
    return s

if __name__ == '__main__':
    main()
